unique_name: Product_DataSet
object_type: dataset
label: Product
columns:
  - name: ID
    data_type: string
  - name: Category
    data_type: string
  - name: Name
    data_type: string
  - name: Price
    data_type: decimal(15,2)
  - name: SKU
    data_type: string
connection_id: con_default_HoleFoods
table: Product
